server:
  http_listen_port: 9080

positions:
  filename: /run/promtail/positions.yaml

clients:
  - url: http://13.234.37.120:3100/loki/api/v1/push  # Replace LOKI_IP with actual Loki IP

scrape_configs:
  - job_name: docker_containers
    static_configs:
      - targets:
          - localhost
        labels:
          job: docker
          host: min-dev # This will be unique for each server
          __path__: /var/lib/docker/containers/*/*.log

    pipeline_stages:
      - json:
          expressions:
            output: log
            stream: stream
            timestamp: time
            container_name: container_name # Add container_name here if available in logs
      - timestamp:
          source: timestamp
          format: RFC3339Nano
      - docker:
      - labels:
          stream:
          container_name: container_name
      - output:
          source: output