# promtail/docker-compose.yml
version: '3'

services:
  promtail:
    image: grafana/promtail:latest
    container_name: promtail-min-dev
    volumes:
      - ./config:/etc/promtail
      - ./positions:/run/promtail
      - /var/log:/var/log:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command: -config.file=/etc/promtail/promtail-config.yaml
    environment:
      - HOSTNAME=min-dev
    restart: unless-stopped